# Generated by Django 5.2 on 2025-04-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='is_upvote',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], default='upvote', max_length=4),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.CharField(default='up', max_length=255),
            preserve_default=False,
        ),
    ]
